Repository jOOQ/jOOQ, pull requests merged in 2019-07, with the labels that each got.

#8114 [#8004] Handle edgecase for Kotlin boolean type
  jOOQ/src/main/java/org/jooq/impl/DefaultRecordMapper.java
Labels: C: Functionality, C: Integration: Kotlin, E: All Editions, P: Medium, T: Enhancement

#8978 Make generatePojoMultiConstructor in JavaGenerator protected
  jOOQ-codegen/src/main/java/org/jooq/codegen/JavaGenerator.java
Labels: C: Code Generation, E: All Editions, P: Medium, T: Defect

#8976 [jOOQ/jOOQ#8939] Support Flyway file ordering in DDLDatabase
  jOOQ-examples/jOOQ-flyway-ddl-example/.gitignore
  jOOQ-examples/jOOQ-flyway-ddl-example/LICENSE.txt
  jOOQ-examples/jOOQ-flyway-ddl-example/README.md
  jOOQ-examples/jOOQ-flyway-ddl-example/pom.xml
  jOOQ-examples/jOOQ-flyway-ddl-example/src/main/resources/db/migration/V1.2__create_author_table.sql
  jOOQ-examples/jOOQ-flyway-ddl-example/src/main/resources/db/migration/V1_3__create_book_table_and_add_records.sql
  jOOQ-examples/jOOQ-flyway-ddl-example/src/main/resources/db/migration/V1__initialise_database.sql
  jOOQ-meta/src/main/java/org/jooq/meta/tools/FilePattern.java
  jOOQ-meta/src/main/java/org/jooq/meta/tools/FlywayFileComparator.java
  jOOQ-meta/src/main/java/org/jooq/meta/tools/FlywayVersion.java
Labels: C: Code Generation, E: All Editions, P: Medium, T: Enhancement
